apiVersion: 1

groups:
  - orgId: 1
    name: network-stability
    folder: alerts
    interval: 60s
    rules:
      - uid: 6
        title: Uptime below 90%
        condition: B
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              editorMode: code
              expr: uptime < 0.90
              hide: false
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: true
              refId: A
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: -100
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: [ ]
                    type: avg
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              downsampler: mean
              expression: A
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
              upsampler: fillna
        for: 5m
        annotations:
          __dashboardUid__: kBQpRdWnk
          __panelId__: '46'
        labels:
          env: testnet
          severity: medium
