apiVersion: 1

groups:
  - orgId: 1
    name: network-health
    folder: alerts
    interval: 60s
    rules:
      - uid: 3
        title: Connected Validator Nodes below 90%
        condition: B
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              editorMode: code
              expr: 'ping_validator_status{instance="push_daemon",job="validators_status"} * (connected{instance="push_daemon",job="validators_status"} / (connected{instance="push_daemon",job="validators_status"} + disconnected{instance="push_daemon",job="validators_status"}))'
              intervalMs: 1000
              maxDataPoints: 43200
              legendFormat: __auto
              range: true
              refId: A
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: -100
            model:
              conditions:
                - evaluator:
                    params:
                      - 0.90
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: '-100'
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: classic_conditions
        for: 1m30s
        annotations:
          "__dashboardUid__": "kBQpRdWnk"
          "__panelId__": "37"
          severity: high
        labels:
          env: testnet