apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord
    receivers:
      - uid: 1
        type: discord
        settings:
          url: DISCORD_WEBHOOK_URL
          use_discord_username: Grafana
          message: |
            {{ template "default.message" . }}
