apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord
    receivers:
      - uid: 1
        type: discord
        settings:
          url: https://discord.com/api/webhooks/1025325437179658280/RtaBNCF-vYinS9OMVLVWL4Ohwsm9jhTv0GMWvG8Doer773qTzu5EwHyjdyJuDRqHUTSP
          use_discord_username: Grafana
          message: |
            {{ template "default.message" . }}
