{
 "title": "C-Chain",
 "tags": [ "Camino" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "validator_job_prefix", "label": "Validators Job Prefix", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Accepted Blocks in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(camino_C_blks_accepted_count{job=~\"$validator_job_prefix\"}[1m]))>0",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Rejected Blocks in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(camino_C_blks_rejected_count{job=~\"$validator_job_prefix\"}[1m]))>0",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Average Block Acceptance Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and acceptance by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(camino_C_blks_accepted_sum{job=~\"$validator_job_prefix\"}[5m]) / rate(camino_C_blks_accepted_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Average Block Rejection Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and rejection by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(camino_C_blks_rejected_sum{job=~\"$validator_job_prefix\"}[5m]) / rate(camino_C_blks_rejected_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Processing Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "camino_C_blks_processing{job=~\"$validator_job_prefix\"}>0",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Incomplete Polls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "camino_C_polls > 0", "legendFormat": "{{company}}" }
   ]
  },
  {
   "title": "Message Handling Time (Total)",
   "type": "timeseries",
   "description": "Measures how much of each second is being spent handling different kinds of messages on the C-Chain.\nThe value for chits, for example, is the number of seconds spent handling chits messages per second, over the last 30 seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(camino_C_handler_pull_query_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(camino_C_handler_push_query_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(camino_C_handler_chits_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(camino_C_handler_accepted_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(camino_C_handler_get_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(camino_C_handler_put_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(camino_C_handler_multiput_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(camino_C_handler_get_ancestors_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(camino_C_handler_get_failed_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(camino_C_handler_query_failed_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(camino_C_handler_get_accepted_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(camino_C_handler_get_ancestors_failed_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(camino_C_handler_app_request_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(camino_C_handler_app_request_failed_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(camino_C_handler_app_response_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "app response"
    },
    {
     "expr": "rate(camino_C_handler_app_gossip_sum{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "app gossip"
    }
   ]
  },
  {
   "title": "Percentage of Successful Queries",
   "type": "timeseries",
   "description": "Percentage of queries for which we receive chits on time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(camino_C_handler_chits_count{job=~\"$validator_job_prefix\"}[5m]) + 1) / (increase(camino_C_handler_chits_count{job=~\"$validator_job_prefix\"}[5m]) + increase(camino_C_handler_query_failed_count{job=~\"$validator_job_prefix\"}[5m]) + 1)*100",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Message Handling Time (per Message)",
   "type": "timeseries",
   "description": "Measures how long each kind of request on the C-Chain takes to handle.\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(camino_C_handler_pull_query_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_pull_query_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(camino_C_handler_push_query_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_push_query_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(camino_C_handler_chits_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_chits_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(camino_C_handler_accepted_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_accepted_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(camino_C_handler_get_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_get_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(camino_C_handler_put_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_put_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(camino_C_handler_multiput_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_multi_put_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(camino_C_handler_get_ancestors_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_get_ancestors_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(camino_C_handler_get_failed_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_get_failed_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(camino_C_handler_query_failed_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_query_failed_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(camino_C_handler_get_accepted_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_get_accepted_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(camino_C_handler_get_ancestors_failed_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_get_ancestors_failed_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(camino_C_handler_app_request_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_app_request_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(camino_C_handler_app_request_failed_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_app_request_failed_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(camino_C_handler_app_response_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_app_response_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "app response"
    },
    {
     "expr": "rate(camino_C_handler_app_gossip_sum{job=~\"$validator_job_prefix\"}[5m])/rate(camino_C_handler_app_gossip_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "app gossip"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "Measures how many of each kind of message are received per second on the C-Chain.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(camino_C_handler_pull_query_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(camino_C_handler_push_query_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(camino_C_handler_chits_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(camino_C_handler_accepted_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(camino_C_handler_get_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(camino_C_handler_put_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(camino_C_handler_multi_put_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(camino_C_handler_get_ancestors_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(camino_C_handler_get_failed_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(camino_C_handler_query_failed_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(camino_C_handler_get_accepted_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(camino_C_handler_get_ancestors_failed_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(camino_C_handler_app_request_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(camino_C_handler_app_request_failed_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(camino_C_handler_app_response_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "app response"
    },
    {
     "expr": "rate(camino_C_handler_app_gossip_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "app gossip"
    }
   ]
  },
  {
   "title": "Block ID Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the cache where the key is the byte representation of the block, and the value is the block's ID",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(camino_C_vm_rpcchainvm_bytes_to_id_cache_hit[5m])/(increase(camino_C_vm_rpcchainvm_bytes_to_id_cache_hit[5m])+increase(camino_C_vm_rpcchainvm_bytes_to_id_cache_miss[5m]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Missing Block Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the missing block cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "increase(camino_C_vm_rpcchainvm_missing_cache_hit[5m])/(increase(camino_C_vm_rpcchainvm_missing_cache_hit[5m])+increase(camino_C_vm_rpcchainvm_missing_cache_miss[5m]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Decided Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the decided block cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "increase(camino_C_vm_rpcchainvm_decided_cache_hit[5m])/(increase(camino_C_vm_rpcchainvm_decided_cache_hit[5m])+increase(camino_C_vm_rpcchainvm_decided_cache_miss[5m]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Unverified Block Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the unverified block cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "increase(camino_C_vm_rpcchainvm_unverified_cache_hit[5m])/(increase(camino_C_vm_rpcchainvm_unverified_cache_hit[5m])+increase(camino_C_vm_rpcchainvm_unverified_cache_miss[5m]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Unprocessed Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "camino_C_handler_unprocessed_msgs_len",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Incoming Messages Expired in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(camino_C_handler_expired[1m])",
     "legendFormat": "{{company}}"
    }
   ]
  }
 ]
}