{
 "title": "Camino Main Dashboard",
 "description": "Home dashboard with the most important indicators for your node and machine",
 "tags": [ "Camino" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "validator_job_prefix", "label": "Validators Job Prefix", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Uptime < 99%",
   "type": "gauge",
   "description": "Uptime as provided via the P-Chain API getCurrentValidators",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "nodeID", "text": "Node Id", "type": "string" },
      { "selector": "uptime", "text": "Uptime", "type": "number" }
     ],
     "expr": "uptime < 0.99",
     "legendFormat": "{{nodeID}}",
     "parser": "backend",
     "root_selector": "result.validators",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://columbus.camino.foundation/ext/bc/P",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"jsonrpc\": \"2.0\",\"method\": \"platform.getCurrentValidators\",\"params\": {},\"id\": 1\n}",
      "headers": [
       { "key": "content-type", "value": "application/json" }
      ],
      "method": "POST",
      "params": [
       { "key": "content", "value": "value" }
      ]
     }
    }
   ]
  },
  {
   "title": "X Chain Vertices",
   "type": "timeseries",
   "description": "Number of accepted and rejected vertices on the X chain in the last minute",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(round(increase(camino_X_vtx_accepted_count{job=~\"$validator_job_prefix\"}[1m])))>0",
     "legendFormat": "Avg. Accepted"
    },
    {
     "expr": "avg(round(increase(camino_X_vtx_rejected_count{job=~\"$validator_job_prefix\"}[1m])))>0",
     "legendFormat": "Avg. Rejected"
    },
    {
     "expr": "bottomk(1, round(increase(camino_X_vtx_accepted_count{job=~\"$validator_job_prefix\"}[1m])))>0",
     "legendFormat": "Validator min acceptances {{company}}"
    },
    {
     "expr": "topk(1, round(increase(camino_X_vtx_rejected_count{job=~\"$validator_job_prefix\"}[1m])))>0",
     "legendFormat": "Validator max rejections {{company}}"
    }
   ]
  },
  {
   "title": "P Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the P chain in the last minute.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(round(increase(camino_P_blks_accepted_count{job=~\"$validator_job_prefix\"}[1m])))>0",
     "legendFormat": "Avg. Accepted"
    },
    {
     "expr": "avg(round(increase(camino_P_blks_rejected_count{job=~\"$validator_job_prefix\"}[1m])))>0",
     "legendFormat": "Avg. Rejected"
    },
    {
     "expr": "bottomk(1, round(increase(camino_P_blks_accepted_count{job=~\"$validator_job_prefix\"}[1m])))>0",
     "legendFormat": "Validator min acceptances {{company}}"
    },
    {
     "expr": "topk(1,round(increase(camino_P_blks_rejected_count{job=~\"$validator_job_prefix\"}[1m])))>0",
     "legendFormat": "Validator max rejections {{company}}"
    }
   ]
  },
  {
   "title": "Proposed P blocks (avg/minimum)",
   "type": "stat",
   "description": "Number of P-Chain blocks this node has proposed on the network in the last day. Since block production on P-Chain is usually below the target rate, every node proposes P blocks.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(round(increase(camino_P_blks_built{job=~\"$validator_job_prefix\"}[$__range])))",
     "legendFormat": "Avg. Proposed P blocks"
    },
    {
     "expr": "bottomk(1, round(increase(camino_P_blks_built{job=~\"$validator_job_prefix\"}[$__range])))",
     "legendFormat": "Min. Proposed P blocks: {{company}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Percentage of CPU used",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"caminogo-machine\", mode=\"idle\"}[1m])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "description": "Percentage of storage filled",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(((node_filesystem_size_bytes{job=~\"caminogo-machine\", fstype=~\"ext4|vfat\"} - node_filesystem_free_bytes{job=~\"caminogo-machine\", fstype=~\"ext4|vfat\"}) / node_filesystem_size_bytes{job=~\"caminogo-machine\", fstype=~\"ext4|vfat\"}) * 100) by (instance)"
    }
   ]
  },
  {
   "title": "Validators connected %",
   "type": "gauge",
   "description": "Percentage of connected validators",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_validator_status{instance=\"push_daemon\",job=\"validators_status\"} * (connected{instance=\"push_daemon\",job=\"validators_status\"} / (connected{instance=\"push_daemon\",job=\"validators_status\"} + disconnected{instance=\"push_daemon\",job=\"validators_status\"}))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Validators connected #",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "ping_validator_status{instance=\"push_daemon\",job=\"validators_status\"} * connected{instance=\"push_daemon\",job=\"validators_status\"}",
     "legendFormat": "Connected"
    },
    {
     "expr": "ping_validator_status{instance=\"push_daemon\",job=\"validators_status\"} * disconnected{instance=\"push_daemon\",job=\"validators_status\"}",
     "legendFormat": "Disconnected"
    }
   ]
  },
  {
   "title": "C Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the C chain in the last minute.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(round(increase(camino_C_blks_accepted_count{job=~\"$validator_job_prefix\"}[1m])))>0",
     "legendFormat": "Avg. Accepted"
    },
    {
     "expr": "avg(round(increase(camino_C_blks_rejected_count{job=~\"$validator_job_prefix\"}[1m])))>0",
     "legendFormat": "Avg. Rejected"
    },
    {
     "expr": "bottomk(1, round(increase(camino_C_blks_accepted_count{job=~\"$validator_job_prefix\"}[1m])))>0",
     "legendFormat": "Validator min acceptances: {{company}}"
    },
    {
     "expr": "topk(1, round(increase(camino_C_blks_rejected_count{job=~\"$validator_job_prefix\"}[1m])))>0",
     "legendFormat": "Validator max rejections: {{company}}"
    }
   ]
  },
  {
   "title": "Proposed C blocks(avg/minimum)",
   "type": "stat",
   "description": "Number of blocks this node has proposed on the C-Chain in the last day. Since C-Chain blocks are produced at a fast rate, block producers are selected by stake weight.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(round(increase(camino_C_blks_built{job=~\"$validator_job_prefix\"}[$__range])))",
     "legendFormat": "Average"
    },
    {
     "expr": "bottomk(1, round(increase(camino_C_blks_built{job=~\"$validator_job_prefix\"}[$__range])))",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Average accepted Blocks/Vertices",
   "type": "bargauge",
   "description": "Number of blocks/vertices accepted in the last minute",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(round(increase(camino_X_vtx_accepted_count{job=~\"$validator_job_prefix\"}[1m])))",
     "legendFormat": "X Chain"
    },
    {
     "expr": "avg(round(increase(camino_P_blks_accepted_count{job=~\"$validator_job_prefix\"}[1m])))",
     "legendFormat": "P Chain"
    },
    {
     "expr": "avg(round(increase(camino_C_blks_accepted_count{job=~\"$validator_job_prefix\"}[1m])))",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Stake connected",
   "type": "stat",
   "description": "Amount of network stake node is currently connected to",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(camino_P_vm_percent_connected{job=~\"$validator_job_prefix\"})"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "bargauge",
   "description": "Number of blocks/vertices currently being processed by the node",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "camino_X_vtx_processing{job=~\"$validator_job_prefix\"}",
     "legendFormat": "X Chain"
    },
    {
     "expr": "camino_P_blks_processing{job=~\"$validator_job_prefix\"}",
     "legendFormat": "P Chain"
    },
    {
     "expr": "camino_C_blks_processing{job=~\"$validator_job_prefix\"}",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Queries success",
   "type": "bargauge",
   "description": "Percentage of successful queries per chain in the last minute",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((increase(camino_X_handler_chits_count{job=~\"$validator_job_prefix\"}[1m]) + 1) / (increase(camino_X_handler_chits_count{job=~\"$validator_job_prefix\"}[1m]) + increase(camino_X_handler_query_failed_count{job=~\"$validator_job_prefix\"}[1m]) + 1))",
     "legendFormat": "X Chain"
    },
    {
     "expr": "avg((increase(camino_P_handler_chits_count{job=~\"$validator_job_prefix\"}[1m]) + 1) / (increase(camino_P_handler_chits_count{job=~\"$validator_job_prefix\"}[1m]) + increase(camino_P_handler_query_failed_count{job=~\"$validator_job_prefix\"}[1m]) + 1)) ",
     "legendFormat": "P Chain"
    },
    {
     "expr": "avg((increase(camino_C_handler_chits_count{job=~\"$validator_job_prefix\"}[1m]) + 1) / (increase(camino_C_handler_chits_count{job=~\"$validator_job_prefix\"}[1m]) + increase(camino_C_handler_query_failed_count{job=~\"$validator_job_prefix\"}[1m]) + 1)) ",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Database Operations Latency (avg / bottom5)",
   "type": "timeseries",
   "description": "How long each database operation is taking on average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(increase(camino_db_put_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_put_count{job=~\"$validator_job_prefix\"}[5m]))",
     "legendFormat": "avg. put"
    },
    {
     "expr": "bottomk(5, increase(camino_db_put_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_put_count{job=~\"$validator_job_prefix\"}[5m]))",
     "legendFormat": "put({{company}})"
    },
    {
     "expr": "avg(increase(camino_db_get_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_get_count{job=~\"$validator_job_prefix\"}[5m]))",
     "legendFormat": "avg. get"
    },
    {
     "expr": "bottomk(5, increase(camino_db_get_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_get_count{job=~\"$validator_job_prefix\"}[5m]))",
     "legendFormat": "get({{company}})"
    },
    {
     "expr": "avg(increase(camino_db_delete_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_delete_count{job=~\"$validator_job_prefix\"}[5m]))",
     "legendFormat": "avg. delete"
    },
    {
     "expr": "bottomk(5, increase(camino_db_delete_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_delete_count{job=~\"$validator_job_prefix\"}[5m]))",
     "legendFormat": "delete({{company}})"
    },
    {
     "expr": "avg(increase(camino_db_has_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_has_count{job=~\"$validator_job_prefix\"}[5m]))",
     "legendFormat": "avg. has"
    },
    {
     "expr": "bottomk(5, increase(camino_db_has_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_has_count{job=~\"$validator_job_prefix\"}[5m]))",
     "legendFormat": "has({{company}})"
    },
    {
     "expr": "increase(camino_db_compact_size_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_compact_size_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(camino_db_batch_put_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_batch_put_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(camino_db_batch_delete_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_batch_delete_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(camino_db_batch_reset_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_batch_reset_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(camino_db_batch_replay_sum{job=~\"$validator_job_prefix\"}[5m])/increase(camino_db_batch_replay_count{job=~\"$validator_job_prefix\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "Top 5 - highest Network Latency",
   "type": "stat",
   "description": "Average time to get a response from a peer",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,camino_requests_average_latency / 1000000)",
     "legendFormat": "{{company}}"
    },
    {
     "expr": "avg(camino_requests_average_latency/ 1000000)",
     "legendFormat": "avg request latency of all nodes in #ms"
    }
   ]
  }
 ]
}