{
 "title": "Network",
 "tags": [ "Camino" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "validator_job_prefix", "label": "Validators Job Prefix", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime average",
   "type": "timeseries",
   "description": "Real uptime of your node as provided by https://docs.camino.foundation/developer/apis/camino-node-apis/p-chain#platformgetcurrentvalidators",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "camino_network_node_uptime_weighted_average{job=~\"$validator_job_prefix\"}",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Rewarding stake",
   "type": "timeseries",
   "description": "Percentage of the stake that view your node as sufficiently online and correct to vote that node be awarded at the end of the staking period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(camino_network_node_uptime_rewarding_stake)"
    }
   ]
  },
  {
   "title": "Network Timing",
   "type": "timeseries",
   "description": "Shows the amount of time this node will wait for a response to a request before considering the request failed, and the average time it takes to get a response to a request.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "camino_requests_current_timeout",
     "legendFormat": "{{company}}[Timeout]"
    },
    {
     "expr": "camino_requests_average_latency",
     "legendFormat": "{{company}}[Response Time]"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "timeseries",
   "description": "Number of outstanding requests related to consensus/bootstrapping. Doesn't include handshake messages.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    { "expr": "camino_requests_outstanding", "legendFormat": "{{company}}" }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(camino_network_accepted_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(camino_network_get_accepted_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(camino_network_get_accepted_frontier_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(camino_network_get_ancestors_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(camino_network_put_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(camino_network_multi_put_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(camino_network_get_version_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(camino_network_get_peerlist_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(camino_network_pull_query_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(camino_network_push_query_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(camino_network_version_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(camino_network_ping_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(camino_network_pong_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(camino_network_get_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(camino_network_chits_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(camino_network_app_gossip_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(camino_network_app_request_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(camino_network_app_response_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Messages Sent per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(camino_network_accepted_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(camino_network_get_accepted_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(camino_network_get_accepted_frontier_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(camino_network_get_ancestors_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(camino_network_put_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(camino_network_multi_put_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(camino_network_get_version_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(camino_network_get_peerlist_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(camino_network_pull_query_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(camino_network_push_query_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(camino_network_version_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(camino_network_ping_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(camino_network_pong_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(camino_network_get_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(camino_network_chits_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(camino_network_app_gossip_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(camino_network_app_request_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(camino_network_app_response_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Messages Received Bandwidth",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(camino_network_accepted_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(camino_network_get_accepted_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(camino_network_get_accepted_frontier_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(camino_network_get_ancestors_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(camino_network_put_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(camino_network_multi_put_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(camino_network_get_version_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(camino_network_get_peerlist_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(camino_network_pull_query_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(camino_network_push_query_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(camino_network_version_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(camino_network_ping_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(camino_network_pong_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(camino_network_get_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(camino_network_chits_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(camino_network_app_gossip_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(camino_network_app_request_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(camino_network_app_response_received_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Messages Sent Bandwidth",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(camino_network_accepted_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(camino_network_get_accepted_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(camino_network_get_accepted_frontier_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(camino_network_get_ancestors_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(camino_network_put_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(camino_network_multi_put_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(camino_network_get_version_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(camino_network_get_peerlist_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(camino_network_pull_query_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(camino_network_push_query_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(camino_network_version_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(camino_network_ping_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(camino_network_pong_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(camino_network_get_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(camino_network_chits_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(camino_network_app_gossip_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(camino_network_app_request_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(camino_network_app_response_sent_bytes{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Average Received Message Size",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(camino_network_accepted_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_accepted_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "increase(camino_network_get_accepted_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_get_accepted_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "increase(camino_network_get_accepted_frontier_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_get_accepted_frontier_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "increase(camino_network_get_ancestors_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_get_ancestors_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "increase(camino_network_put_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_put_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(camino_network_multi_put_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_multi_put_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "increase(camino_network_get_version_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_get_version_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "increase(camino_network_get_peerlist_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_get_peerlist_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "increase(camino_network_pull_query_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_pull_query_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "increase(camino_network_push_query_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_push_query_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "increase(camino_network_version_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_version_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "increase(camino_network_ping_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_ping_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "increase(camino_network_pong_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_pong_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "increase(camino_network_get_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_get_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(camino_network_chits_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_chits_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "increase(camino_network_app_gossip_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_app_gossip_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "increase(camino_network_app_request_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_app_request_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "increase(camino_network_app_response_received_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_app_response_received{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Average Sent Message Size",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(camino_network_accepted_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_accepted_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "increase(camino_network_get_accepted_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_get_accepted_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "increase(camino_network_get_accepted_frontier_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_get_accepted_frontier_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "increase(camino_network_get_ancestors_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_get_ancestors_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "increase(camino_network_put_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_put_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(camino_network_multi_put_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_multi_put_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "increase(camino_network_get_version_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_get_version_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "increase(camino_network_get_peerlist_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_get_peerlist_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "increase(camino_network_pull_query_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_pull_query_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "increase(camino_network_push_query_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_push_query_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "increase(camino_network_version_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_version_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "increase(camino_network_ping_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_ping_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "increase(camino_network_pong_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_pong_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "increase(camino_network_get_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_get_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(camino_network_chits_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_chits_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "increase(camino_network_app_gossip_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_app_gossip_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "increase(camino_network_app_request_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_app_request_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "increase(camino_network_app_response_sent_bytes{job=~\"$validator_job_prefix\"}[1m])/increase(camino_network_app_response_sent{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Queries Sent per Accepted Container",
   "type": "timeseries",
   "description": "Considers the X-Chain, P-Chain and C-Chain. A lower value indicates vote pipelining (good.) A higher value indicates failed polls (not good.)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "($A + $B) / ($C + $D + $E)", "type": "math" }
   ]
  },
  {
   "title": "Messages Awaiting Send",
   "type": "timeseries",
   "description": "Number of messages that are queued to be sent to peers",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "targets": [
    {
     "expr": "camino_network_throttler_outbound_awaiting_release",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Benched stake",
   "type": "timeseries",
   "description": "Amount of the stake in AVAX that is benched (ignored) because the nodes are unhealthy",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "camino_X_benchlist_benched_weight/1000000000",
     "legendFormat": "X chain"
    },
    {
     "expr": "camino_P_benchlist_benched_weight/1000000000",
     "legendFormat": "P Chain"
    },
    {
     "expr": "camino_C_benchlist_benched_weight/1000000000",
     "legendFormat": "C Chain"
    }
   ]
  },
  { "title": "Inbound Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Inbound Byte Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire bytes from the inbound message throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "camino_network_byte_throttler_inbound_awaiting_acquire",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Remaining Validator Bytes",
   "type": "timeseries",
   "description": "Number of bytes left in the validator byte allocation of the inbound message throttler",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "camino_network_byte_throttler_inbound_remaining_validator_bytes",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Acquire Latency",
   "type": "timeseries",
   "description": "The amount of time, on average, that we wait to acquire bytes from the throttler before reading a message.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(camino_network_byte_throttler_inbound_acquire_latency_sum[2m])/increase(camino_network_byte_throttler_inbound_acquire_latency_count[2m])",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Inbound Buffer Throttler Acquire Latency",
   "type": "timeseries",
   "description": "The amount of time, on average, that we wait to acquire from the throttler before reading a message.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(camino_network_buffer_throttler_inbound_acquire_latency_sum[2m])/increase(camino_network_buffer_throttler_inbound_acquire_latency_count[2m])",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Awaiting Release (Messages Processing)",
   "type": "timeseries",
   "description": "Number of messages that are currently being handled and haven't yet returned their bytes to the inbound message throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "expr": "camino_network_byte_throttler_inbound_awaiting_release",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Inbound Buffer Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire from the inbound message buffer throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "expr": "camino_network_buffer_throttler_inbound_awaiting_acquire",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Remaining At-Large Bytes",
   "type": "timeseries",
   "description": "Number of bytes left in the at-large byte allocation of the inbound message throttler",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "camino_network_byte_throttler_inbound_remaining_at_large_bytes",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire bytes from the inbound bandwidth throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "camino_network_bandwidth_throttler_inbound_awaiting_acquire",
     "legendFormat": "{{company}}"
    }
   ]
  },
  { "title": "Outbound Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Outbound Throttler Remaining At-Large Bytes",
   "type": "timeseries",
   "description": "Number of bytes left in the at-large byte allocation of the outbound message throttler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "camino_network_throttler_outbound_remaining_at_large_bytes",
     "legendFormat": "{{company}}"
    }
   ]
  },
  {
   "title": "Outbound Throttler Remaining Validator Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the validator byte allocation of the outbound message throttler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "camino_network_throttler_outbound_remaining_validator_bytes",
     "legendFormat": "{{company}}"
    }
   ]
  },
  { "title": "Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Messages Failed To Send per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(camino_network_accepted_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(camino_network_get_accepted_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(camino_network_get_accepted_frontier_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(camino_network_get_ancestors_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(camino_network_put_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(camino_network_multi_put_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(camino_network_get_version_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(camino_network_get_peerlist_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(camino_network_pull_query_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(camino_network_push_query_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(camino_network_version_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(camino_network_ping_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(camino_network_pong_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(camino_network_chits_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(camino_network_app_gossip_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(camino_network_app_request_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(camino_network_app_response_failed{job=~\"$validator_job_prefix\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Messages Failed To Parse per Minute",
   "type": "timeseries",
   "description": "Number of messages that could not be parsed because they were of unknown type or invalidly formatted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "increase(camino_network_msgs_failed_to_parse[1m])>0",
     "legendFormat": "Failed to Parse"
    }
   ]
  },
  {
   "title": "Inbound Messages Dropped in Last Minute",
   "type": "timeseries",
   "description": "Number of inbound messages dropped (not processed) due to expiration in last minute.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "increase(camino_P_handler_expired[1m])+increase(camino_C_handler_expired[1m])+increase(camino_X_handler_expired[1m])",
     "legendFormat": "Messages Dropped"
    }
   ]
  },
  {
   "title": "Outbound Messages Dropped in Last Minute",
   "type": "timeseries",
   "description": "Number of outbound messages dropped (not sent) due to rate-limiting in the last minute",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
   "targets": [
    {
     "expr": "increase(camino_network_throttler_outbound_acquire_failures[1m])",
     "legendFormat": "Messages Dropped"
    }
   ]
  },
  {
   "title": "Inbound Connections Dropped due to Rate-Limiting per Minute",
   "type": "timeseries",
   "description": "Number of inbound connections dropped due to inbound connection rate-limiting",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
   "targets": [
    {
     "expr": "increase(camino_network_inbound_conn_throttler_rate_limited[1m])",
     "legendFormat": "Rate-Limited"
    }
   ]
  },
  { "title": "Compression", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Average Message Compression Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(increase(camino_network_codec_multi_put_compress_time_sum[5m])+1)/(increase(camino_network_codec_multi_put_compress_time_count[5m])+1)",
     "legendFormat": "Multiput"
    },
    {
     "expr": "(increase(camino_network_codec_push_query_compress_time_sum[5m])+1)/(increase(camino_network_codec_push_query_compress_time_count[5m])+1)",
     "legendFormat": "Push Query"
    },
    {
     "expr": "(increase(camino_network_codec_put_compress_time_sum[5m])+1)/(increase(camino_network_codec_put_compress_time_count[5m])+1)",
     "legendFormat": "Put"
    },
    {
     "expr": "(increase(camino_network_codec_peerlist_compress_time_sum[5m])+1)/(increase(camino_network_codec_peerlist_compress_time_count[5m])+1)",
     "legendFormat": "Peer List"
    },
    {
     "expr": "(increase(camino_network_codec_app_gossip_compress_time_sum[5m])+1)/(increase(camino_network_codec_app_gossip_compress_time_count[5m])+1)",
     "legendFormat": "App Gossip"
    },
    {
     "expr": "(increase(camino_network_codec_app_request_compress_time_sum[5m])+1)/(increase(camino_network_codec_app_request_compress_time_count[5m])+1)",
     "legendFormat": "App Request"
    },
    {
     "expr": "(increase(camino_network_codec_app_response_compress_time_sum[5m])+1)/(increase(camino_network_codec_app_response_compress_time_count[5m])+1)",
     "legendFormat": "App Response"
    }
   ]
  },
  {
   "title": "Total Message Compression Time per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(camino_network_codec_multi_put_compress_time_sum[5m])",
     "legendFormat": "Multiput"
    },
    {
     "expr": "rate(camino_network_codec_push_query_compress_time_sum[5m])",
     "legendFormat": "Push Query"
    },
    {
     "expr": "rate(camino_network_codec_put_compress_time_sum[5m])",
     "legendFormat": "Put"
    },
    {
     "expr": "rate(camino_network_codec_peerlist_compress_time_sum[5m])",
     "legendFormat": "Peer List"
    },
    {
     "expr": "rate(camino_network_codec_app_gossip_compress_time_sum[5m])",
     "legendFormat": "App Gossip"
    },
    {
     "expr": "rate(camino_network_codec_app_request_compress_time_sum[5m])",
     "legendFormat": "App Request"
    },
    {
     "expr": "rate(camino_network_codec_app_response_compress_time_sum[5m])",
     "legendFormat": "App Response"
    }
   ]
  },
  {
   "title": "Bytes Saved by Compression",
   "type": "timeseries",
   "description": "Rate at which we save bytes (don't send/receive them over the network) by compressing messages/receiving compressed messages.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(camino_network_multi_put_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound Multiput"
    },
    {
     "expr": "rate(camino_network_multi_put_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound Multiput"
    },
    {
     "expr": "rate(camino_network_put_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound Put"
    },
    {
     "expr": "rate(camino_network_put_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound Put"
    },
    {
     "expr": "rate(camino_network_push_query_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound Push Query"
    },
    {
     "expr": "rate(camino_network_push_query_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound Push Query"
    },
    {
     "expr": "rate(camino_network_peerlist_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound Peer List"
    },
    {
     "expr": "rate(camino_network_peerlist_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound Peer List"
    },
    {
     "expr": "rate(camino_network_app_gossip_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound App Gossip"
    },
    {
     "expr": "rate(camino_network_app_gossip_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound App Gossip"
    },
    {
     "expr": "rate(camino_network_app_request_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound App Request"
    },
    {
     "expr": "rate(camino_network_app_request_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound App Request"
    },
    {
     "expr": "rate(camino_network_app_response_compression_saved_received_bytes_sum[5m])",
     "legendFormat": "Inbound App Response"
    },
    {
     "expr": "rate(camino_network_app_response_compression_saved_sent_bytes_sum[5m])",
     "legendFormat": "Outbound App Response"
    }
   ]
  }
 ]
}